feat: :sparkles: added search to home page
lblod/frontend-burgernabije-besluitendatabank pull request #140
Opened 2023-09-28 09:10 UTC by snenenenenenene

2023-10-03 08:32 UTC, aliokan requested changes
@snenenenenenene I first thought that it was worth creating a component to encapsulate the input logic. But after all, there is a good chance that the input keyword on home and list page will have different behavior or design in the future. 

Except the remaining `console.log` we are good to move forward. 

Good job! :+1:

2023-10-03 08:32 UTC, aliokan commented on app/controllers/home.ts
> +    console.log(this.value);
**Issue:** @snenenenenenene oups ;)

2023-10-03 08:32 UTC, aliokan commented on app/controllers/home.ts
> +  @tracked value = '';
**Nitpick:** Using a more meaningful name would improve readability and avoid confusion if other input text is added in the future 🙃

2023-10-04 08:28 UTC, snenenenenenene commented
@aliokan, fixed it! Thanks for the feedback <3

2023-10-04 18:51 UTC, aliokan approved these changes
Tested locally, looks good! :+1: 

LGTM! :rocket:

2023-10-04 18:52 UTC, merged